name: Checkov Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop ]

jobs:
    checkov:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout
          uses: actions/checkout@v2

        - name: Checkov Scan
          uses: PISC-CODEIA-7/central-ci-cd/.github/actions/ci/sec/checkov@develop

    





