name: Terraform Test with localstack

on:
  push:
    branches-ignore:
      - "main"

jobs:

  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run terraform validate
        run: |
          terraform -chdir=tests init
          terraform -chdir=tests validate


  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: asdf_install
        uses: asdf-vm/actions/install@v1
      
      - name: Start Localstack
        run: |
          pip install localstack
          docker pull localstack/localstack
          localstack start -d
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30
      
      - name: Run Terraform Plan
        run: |
          terraform -chdir=tests init
          terraform -chdir=tests plan
      
      - name: Run Terraform apply
        run: |
          terraform -chdir=tests init
          terraform -chdir=tests apply -auto-approve