name: TFSec Scan

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop ]

jobs:
    TFsec:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout
          uses: actions/checkout@v2

        - name: TFsec Scan
          uses: PISC-CODEIA-7/central-ci-cd/.github/actions/ci/sec/tfsec@develop
    

