name: Trivy Sbom

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ develop ]

jobs:
    Trivy-sbom:
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: write
            security-events: write
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: TFsec Scan
          uses: PISC-CODEIA-7/central-ci-cd/.github/actions/ci/sec/trivy-sbom@develop
